{{- if .Values.serviceAccount.create -}}
apiVersion: {{ .Values.apiVersion }}
kind: ServiceAccount
metadata:
  name: {{ include "nfs-server.serviceAccountName" . }}
  namespace: {{ include "nfs-server.namespace" .}}
  labels:
    {{- include "nfs-server.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
